### ISSUE TITLE
Option to default to popout stream on stream click

### ISSUE THREAD

**Issue by Dahduh** [Seldszar/Gumbo#38]
**Is your feature request related to a problem? Please describe.**
Currently you click the stream and it opens the twitch page. You can also click the dots next to the stream title to open the stream in a popout tab - something that I think should be toggleable! 

**Describe the solution you'd like**
Create a toggle in settings to automatically open streams in popout. 

**Describe alternatives you've considered**
Being sad.

**Additional context**
Nothing to add other than my thanks for the superb extension!

**Comment by placchio** [comment]
This is actually the only issue i have with this overall really good extension.
I only browser in incognito mode and there is no way to automatically open streams in the same windows... im always forced to click the right mouse button to do so, plus cant use the dots on the right because it would always open the streams in another window. 

So i agree, adding an option where you can choose how to open streams (in my case on a new tab but always in the same window) would be really helpful.

**Comment by Seldszar** [comment]
Already done for the next release: https://github.com/Seldszar/Gumbo/commit/58abfded728ec9caf0edece46105c8fa7eee6e17

**Comment by Dahduh** [comment]
> Already done for the next release: [58abfde](https://github.com/Seldszar/Gumbo/commit/58abfded728ec9caf0edece46105c8fa7eee6e17)

You're a fucking god.
