### ISSUE TITLE
"Request failed with status code 401 Unauthorized"

### ISSUE THREAD

**Issue by GozenG** [Seldszar/Gumbo#44]
I'm on Firefox Nightly, 
and since this afternoon (approximatively 4pm GMT), Gumbo stopped working for me and I got a blank page with only "Request failed with status code 401 Unauthorized" written on it.
And ultimately showing streams that were online when it last worked
![New Issue · SeldszarGumbo - Firefox Nightly](https://user-images.githubusercontent.com/42277347/166119426-5bd6f15e-24f7-4243-83b6-2a6bcbd119ce.jpg)

**Comment by 000744210** [comment]
I believe it has to do with the token becoming outdated. Eventually the extension will renew it and it will become fixed. It has only happened once to me but it fixed itself within an hour.

**Comment by GozenG** [comment]
last time I encountered this time of behaviour with such extension (not this one, but the previous one I used) it have never been fixed, which lead me to find and use Gumbo in the first place ^^" 
I hope you're right tho, I really don't want to search a new one...

**Comment by Seldszar** [comment]
Is it happening even after relogging?

**Comment by GozenG** [comment]
okay now, I feel silly ^^"

thanks a lot, it worked ! everything is back in working status

**Comment by 000744210** [comment]
This seems to be a popular problem people are going to encounter. I don't know much about the twitch API but from my memory the app needs to refetch new tokens once and awhile. Would it be possible to fix this by trying to refetch and update the latest tokens when this error occurs?

**Comment by Seldszar** [comment]
It could be a solution, but requires a server endpoint because I don't want to expose the client secret. I might consider this solution if people are complaining about it, but having to relog every 54 days or after a password change isn't the end of the world, and I even updated so it's easier to see if the extension is connected or not, and clears the access token if it expired.

And if your issue wasn't resolved after a relog, it might be an issue on Twitch side and implementing a token refresh wouldn't change anything.
