### ISSUE TITLE
Uh-oh Gumbo is not responding anymore.

### ISSUE THREAD

**Issue by BrianJ20** [Seldszar/Gumbo#50]
Often i encounter the below message. I can not reproduce it with any reliability.
It can happen after Windows resumes from hibernation, but also after a cold boot.  I've seen it after force closing chrome.exe and then restarting it again.

![Untitled](https://user-images.githubusercontent.com/92690930/168115444-f3642f96-6c69-482b-b238-b20acf946d2e.jpg)

I'm not sure this is an actual bug, but if you have any idea on how i can deal with this.

 Windows 11 latest stable
Chrome latest stable

**Comment by Seldszar** [comment]
It's being caused by the background service worker randomly breaking, putting the extension in a limbo state. It's a known issue, which is unfortunately on the hands of the Chromium team (https://bugs.chromium.org/p/chromium/issues/detail?id=1271154).

So, instead of leaving as is and constantly receiving tickets about the extension being unresponsive and telling them to re-install the extension, I added this message with this reload button to make things easier.
