### ISSUE TITLE
Game Name is way too small now

### ISSUE THREAD

**Issue by mryx007** [Seldszar/Gumbo#72]
The names of the games are now way too small and too close to the streamers names. It was much better before . It would be better if they were colored, as was suggested. but you have swapped the position and made it smaller. 

![Unbenannt](https://user-images.githubusercontent.com/106607032/172024971-1fe1acbe-872a-4ed2-8fef-40d0a86d41fb.jpg)

**Comment by Seldszar** [comment]
Does this compromise work for you?

![image](https://user-images.githubusercontent.com/3079214/172051978-93b7b1b9-2fc1-464b-90e3-66d44a684480.png)

**Comment by mryx007** [comment]
> Does this compromise work for you?
> 
> ![image](https://user-images.githubusercontent.com/3079214/172051978-93b7b1b9-2fc1-464b-90e3-66d44a684480.png)

Do we need a compromise? Yes, you can make the font bigger in the settings, but then you still don't see it so well. Can't we do it the way it was suggested? For me this is not a good solution but I will have to deal with it because the app is otherwise very good

**Comment by Seldszar** [comment]
The color suggestion was really bad to my eyes, especially the color choice. I still don't understand the reason behind besides making the whole design hideous. Using the primary color would have been a better suggestion but it still doesn't make any sense because the info is always at the same place.

Maybe in your case, it's more about the base text color being too bright, which can be fixed without hesitations with a darker gray.

I'll revert to what it was before and fix the base text color.
